export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const DELETE_INGREDIENTS = 'DELETE_INGREDIENTS';
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';
export const ADD_PRICE = 'ADD_PRICE';
export const COUNT_INGREDIENTS = 'COUNT_INGREDIENTS';





